### ISSUE TITLE
Stage 1 工作内容

### ISSUE THREAD

**Issue by Xooone47** [Xooone47/The-Carpenter-s-House#5]
### UI设计：

**使用ProcessOn，完成后将终稿导出上传到Q群**
首页：黎思奇
捐赠物品页：李皓玮
活动信息页：王正
志工招募页：李姣姣
简介及联系方式页：曹开翀
登录后台页面、查看捐赠物品清单页、查看应聘信息页、活动发布页（后台）：刘忠锜
### 知识储备
1. 前端
   前端使用Bootstrap框架开发，可提前熟悉一下栅格系统及框架的组件
2. 后台
   PHP、SQL

**Comment by Xooone47** [comment]
![-index](https://cloud.githubusercontent.com/assets/7253061/13959842/b91f4268-f090-11e5-8ef7-ae8a62af4452.png)

**Comment by FOOLHOLI** [comment]
![default](https://cloud.githubusercontent.com/assets/12816777/13977441/f17e98a2-f103-11e5-9604-b32ba8408e5f.png)

**Comment by c960917** [comment]
![26wg zfol npsqt zl47 q](https://cloud.githubusercontent.com/assets/17974281/13977737/815e9aa6-f106-11e5-83eb-a4e6b1d3f2e8.png)

**Comment by LJIAOJIAO** [comment]
![default](https://cloud.githubusercontent.com/assets/17949937/13977799/f7a793e8-f106-11e5-9e9a-01e3a04d618f.png)

**Comment by 972751550** [comment]
![1](https://cloud.githubusercontent.com/assets/18022978/13978039/b3779824-f108-11e5-9e6d-e06bfc6af6cc.png)
